"""Add enterprise order management models

Revision ID: 0f31aecb9b1c
Revises: 0006_catchup_missing_columns
Create Date: 2026-03-07 05:12:13.484391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f31aecb9b1c'
down_revision: Union[str, Sequence[str], None] = '0006_catchup_missing_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_modifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('modification_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('old_total', sa.Float(), nullable=False),
    sa.Column('new_total', sa.Float(), nullable=False),
    sa.Column('modification_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_modifications_id'), 'order_modifications', ['id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(length=100), nullable=False),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('auth_code', sa.String(length=50), nullable=True),
    sa.Column('card_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_transaction_id')
    )
    op.create_index(op.f('ix_payment_transactions_id'), 'payment_transactions', ['id'], unique=False)
    op.create_table('tip_distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('tip_amount', sa.Float(), nullable=False),
    sa.Column('distributed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tip_distributions_id'), 'tip_distributions', ['id'], unique=False)
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_customers_is_active'), table_name='customers')
    op.create_index('ix_customers_phone_is_active', 'customers', ['phone', 'is_active'], unique=False)
    op.alter_column('inventory_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_inventory_items_is_active'), table_name='inventory_items')
    op.create_foreign_key(None, 'menu_categories', 'menu_categories', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'menu_items', 'inventory_items', ['inventory_item_id'], ['id'])
    op.add_column('order_items', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('order_items', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('order_items', sa.Column('prepared_by', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('is_voided', sa.Boolean(), nullable=True))
    op.add_column('order_items', sa.Column('void_reason', sa.String(length=255), nullable=True))
    op.add_column('order_items', sa.Column('voided_by', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('voided_at', sa.DateTime(), nullable=True))
    op.add_column('order_items', sa.Column('added_by', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('added_at', sa.DateTime(), nullable=True))
    op.add_column('order_items', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'users', ['prepared_by'], ['id'])
    op.create_foreign_key(None, 'order_items', 'users', ['voided_by'], ['id'])
    op.create_foreign_key(None, 'order_items', 'users', ['added_by'], ['id'])
    op.create_foreign_key(None, 'order_items', 'users', ['modified_by'], ['id'])
    op.add_column('payments', sa.Column('tip_amount', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('parent_payment_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('transaction_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('auth_code', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('card_type', sa.String(length=50), nullable=True))
    op.add_column('payments', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('reason', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('payments_order_id_key'), 'payments', type_='unique')
    op.create_foreign_key(None, 'payments', 'payments', ['parent_payment_id'], ['id'])
    op.alter_column('purchase_receipts', 'is_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_purchase_receipts_is_cancelled'), table_name='purchase_receipts')
    op.alter_column('shifts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_shifts_is_active'), table_name='shifts')
    op.create_foreign_key(None, 'tables', 'orders', ['current_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.create_index(op.f('ix_shifts_is_active'), 'shifts', ['is_active'], unique=False)
    op.alter_column('shifts', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index(op.f('ix_purchase_receipts_is_cancelled'), 'purchase_receipts', ['is_cancelled'], unique=False)
    op.alter_column('purchase_receipts', 'is_cancelled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_unique_constraint(op.f('payments_order_id_key'), 'payments', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('payments', 'reason')
    op.drop_column('payments', 'status')
    op.drop_column('payments', 'card_type')
    op.drop_column('payments', 'auth_code')
    op.drop_column('payments', 'transaction_id')
    op.drop_column('payments', 'parent_payment_id')
    op.drop_column('payments', 'tip_amount')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'modified_at')
    op.drop_column('order_items', 'modified_by')
    op.drop_column('order_items', 'added_at')
    op.drop_column('order_items', 'added_by')
    op.drop_column('order_items', 'voided_at')
    op.drop_column('order_items', 'voided_by')
    op.drop_column('order_items', 'void_reason')
    op.drop_column('order_items', 'is_voided')
    op.drop_column('order_items', 'prepared_by')
    op.drop_column('order_items', 'completed_at')
    op.drop_column('order_items', 'started_at')
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.drop_constraint(None, 'menu_categories', type_='foreignkey')
    op.create_index(op.f('ix_inventory_items_is_active'), 'inventory_items', ['is_active'], unique=False)
    op.alter_column('inventory_items', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index('ix_customers_phone_is_active', table_name='customers')
    op.create_index(op.f('ix_customers_is_active'), 'customers', ['is_active'], unique=False)
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_tip_distributions_id'), table_name='tip_distributions')
    op.drop_table('tip_distributions')
    op.drop_index(op.f('ix_payment_transactions_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_order_modifications_id'), table_name='order_modifications')
    op.drop_table('order_modifications')
    # ### end Alembic commands ###
