"""Add business intelligence and sales forecasting models

Revision ID: 10ea20f3a185
Revises: f48514f3d0fb
Create Date: 2026-03-07 05:32:54.437864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ea20f3a185'
down_revision: Union[str, Sequence[str], None] = 'f48514f3d0fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=20), nullable=False),
    sa.Column('comparison_period', sa.String(length=20), nullable=False),
    sa.Column('comparison_value', sa.Float(), nullable=True),
    sa.Column('change_percentage', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('achievement_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_metrics_id'), 'business_metrics', ['id'], unique=False)
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_name', sa.String(length=100), nullable=False),
    sa.Column('widget_type', sa.String(length=20), nullable=False),
    sa.Column('dashboard_name', sa.String(length=50), nullable=False),
    sa.Column('position_x', sa.Integer(), nullable=True),
    sa.Column('position_y', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=False),
    sa.Column('refresh_interval', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_widgets_id'), 'dashboard_widgets', ['id'], unique=False)
    op.create_table('financial_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_type', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('food_revenue', sa.Float(), nullable=False),
    sa.Column('beverage_revenue', sa.Float(), nullable=False),
    sa.Column('other_revenue', sa.Float(), nullable=True),
    sa.Column('food_cost', sa.Float(), nullable=False),
    sa.Column('beverage_cost', sa.Float(), nullable=False),
    sa.Column('labor_cost', sa.Float(), nullable=False),
    sa.Column('overhead_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('gross_profit', sa.Float(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('gross_margin', sa.Float(), nullable=False),
    sa.Column('net_margin', sa.Float(), nullable=False),
    sa.Column('table_turnover_rate', sa.Float(), nullable=False),
    sa.Column('seat_occupancy_rate', sa.Float(), nullable=False),
    sa.Column('avg_check_size', sa.Float(), nullable=False),
    sa.Column('covers_per_hour', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_reports_id'), 'financial_reports', ['id'], unique=False)
    op.create_table('sales_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('forecast_type', sa.String(length=20), nullable=False),
    sa.Column('predicted_revenue', sa.Float(), nullable=False),
    sa.Column('predicted_orders', sa.Integer(), nullable=False),
    sa.Column('predicted_customers', sa.Integer(), nullable=False),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_forecasts_id'), 'sales_forecasts', ['id'], unique=False)
    op.create_table('business_metric_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('dimension_value', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('contribution_percentage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['business_metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_metric_details_id'), 'business_metric_details', ['id'], unique=False)
    op.create_table('menu_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('total_quantity', sa.Integer(), nullable=False),
    sa.Column('avg_order_quantity', sa.Float(), nullable=False),
    sa.Column('profit_margin', sa.Float(), nullable=False),
    sa.Column('cost_percentage', sa.Float(), nullable=False),
    sa.Column('popularity_score', sa.Float(), nullable=False),
    sa.Column('profitability_score', sa.Float(), nullable=False),
    sa.Column('menu_engineering_category', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_performance_id'), 'menu_performance', ['id'], unique=False)
    op.create_table('sales_forecast_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forecast_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('predicted_quantity', sa.Integer(), nullable=False),
    sa.Column('predicted_revenue', sa.Float(), nullable=False),
    sa.Column('seasonality_factor', sa.Float(), nullable=True),
    sa.Column('trend_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['forecast_id'], ['sales_forecasts.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_forecast_items_id'), 'sales_forecast_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_forecast_items_id'), table_name='sales_forecast_items')
    op.drop_table('sales_forecast_items')
    op.drop_index(op.f('ix_menu_performance_id'), table_name='menu_performance')
    op.drop_table('menu_performance')
    op.drop_index(op.f('ix_business_metric_details_id'), table_name='business_metric_details')
    op.drop_table('business_metric_details')
    op.drop_index(op.f('ix_sales_forecasts_id'), table_name='sales_forecasts')
    op.drop_table('sales_forecasts')
    op.drop_index(op.f('ix_financial_reports_id'), table_name='financial_reports')
    op.drop_table('financial_reports')
    op.drop_index(op.f('ix_dashboard_widgets_id'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    op.drop_index(op.f('ix_business_metrics_id'), table_name='business_metrics')
    op.drop_table('business_metrics')
    # ### end Alembic commands ###
