"""sqlalchemy_2_0_final_migration

Revision ID: 2e028cf768e7
Revises: ac94508acf75
Create Date: 2026-03-10 09:24:40.240782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e028cf768e7'
down_revision: Union[str, Sequence[str], None] = 'ac94508acf75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'last_visit_date')
    op.drop_column('customers', 'avg_order_value')
    op.drop_column('customers', 'preferred_items')
    op.drop_column('customers', 'churn_risk')
    op.drop_column('customers', 'visit_count')
    op.drop_column('customers', 'loyalty_score')
    op.create_index('ix_inventory_items_active_stock', 'inventory_items', ['is_active', 'quantity'], unique=False)
    op.create_index('ix_inventory_items_last_updated', 'inventory_items', ['last_updated'], unique=False)
    op.create_index('ix_inventory_items_min_quantity', 'inventory_items', ['min_quantity'], unique=False)
    op.create_index('ix_inventory_items_name', 'inventory_items', ['name'], unique=False)
    op.create_index('ix_inventory_items_supplier', 'inventory_items', ['supplier'], unique=False)
    op.drop_constraint(op.f('order_items_modified_by_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_voided_by_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_added_by_fkey'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_prepared_by_fkey'), 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'prepared_by')
    op.drop_column('order_items', 'modified_by')
    op.drop_column('order_items', 'voided_at')
    op.drop_column('order_items', 'started_at')
    op.drop_column('order_items', 'modified_at')
    op.drop_column('order_items', 'voided_by')
    op.drop_column('order_items', 'is_voided')
    op.drop_column('order_items', 'added_at')
    op.drop_column('order_items', 'added_by')
    op.drop_column('order_items', 'completed_at')
    op.drop_column('order_items', 'void_reason')
    op.create_index('ix_orders_customer_id_created_at', 'orders', ['customer_id', 'created_at'], unique=False)
    op.create_index('ix_orders_status_paid_at', 'orders', ['status', 'paid_at'], unique=False)
    op.create_index('ix_orders_waiter_id_created_at', 'orders', ['waiter_id', 'created_at'], unique=False)
    op.drop_column('orders', 'preparation_started_at')
    op.drop_column('orders', 'priority')
    op.drop_column('orders', 'estimated_completion')
    op.drop_column('orders', 'ready_at')
    op.create_unique_constraint(None, 'payments', ['order_id'])
    op.drop_constraint(op.f('payments_parent_payment_id_fkey'), 'payments', type_='foreignkey')
    op.drop_column('payments', 'reason')
    op.drop_column('payments', 'transaction_id')
    op.drop_column('payments', 'auth_code')
    op.drop_column('payments', 'tip_amount')
    op.drop_column('payments', 'card_type')
    op.drop_column('payments', 'parent_payment_id')
    op.drop_column('payments', 'status')
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_index('ix_users_role_is_active', 'users', ['role', 'is_active'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_role_is_active', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.add_column('payments', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('parent_payment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('card_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('tip_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('auth_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('transaction_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('payments_parent_payment_id_fkey'), 'payments', 'payments', ['parent_payment_id'], ['id'])
    op.drop_constraint(None, 'payments', type_='unique')
    op.add_column('orders', sa.Column('ready_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('estimated_completion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('preparation_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index('ix_orders_waiter_id_created_at', table_name='orders')
    op.drop_index('ix_orders_status_paid_at', table_name='orders')
    op.drop_index('ix_orders_customer_id_created_at', table_name='orders')
    op.add_column('order_items', sa.Column('void_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('added_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('is_voided', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('voided_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('voided_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('modified_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('order_items', sa.Column('prepared_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('order_items_prepared_by_fkey'), 'order_items', 'users', ['prepared_by'], ['id'])
    op.create_foreign_key(op.f('order_items_added_by_fkey'), 'order_items', 'users', ['added_by'], ['id'])
    op.create_foreign_key(op.f('order_items_voided_by_fkey'), 'order_items', 'users', ['voided_by'], ['id'])
    op.create_foreign_key(op.f('order_items_modified_by_fkey'), 'order_items', 'users', ['modified_by'], ['id'])
    op.drop_index('ix_inventory_items_supplier', table_name='inventory_items')
    op.drop_index('ix_inventory_items_name', table_name='inventory_items')
    op.drop_index('ix_inventory_items_min_quantity', table_name='inventory_items')
    op.drop_index('ix_inventory_items_last_updated', table_name='inventory_items')
    op.drop_index('ix_inventory_items_active_stock', table_name='inventory_items')
    op.add_column('customers', sa.Column('loyalty_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('churn_risk', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('preferred_items', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('avg_order_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('last_visit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
