"""Add staff management and performance tracking models

Revision ID: 362f3ed8cd56
Revises: f83d1ac08cca
Create Date: 2026-03-07 05:22:57.941429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '362f3ed8cd56'
down_revision: Union[str, Sequence[str], None] = 'f83d1ac08cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.create_table('staff_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('performance_date', sa.Date(), nullable=False),
    sa.Column('orders_served', sa.Integer(), nullable=True),
    sa.Column('revenue_generated', sa.Float(), nullable=True),
    sa.Column('table_turnover', sa.Integer(), nullable=True),
    sa.Column('customer_satisfaction', sa.Integer(), nullable=True),
    sa.Column('attendance_score', sa.Integer(), nullable=True),
    sa.Column('tips_received', sa.Float(), nullable=True),
    sa.Column('hours_worked', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_performance_id'), 'staff_performance', ['id'], unique=False)
    op.create_table('staff_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=False),
    sa.Column('shift_type', sa.String(length=20), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('optimization_score', sa.Float(), nullable=True),
    sa.Column('assignment_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_schedules_id'), 'staff_schedules', ['id'], unique=False)
    op.create_table('shift_swap_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_shift_id', sa.Integer(), nullable=False),
    sa.Column('target_shift_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('target_staff_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_shift_id'], ['staff_schedules.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_shift_id'], ['staff_schedules.id'], ),
    sa.ForeignKeyConstraint(['target_staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_swap_requests_id'), 'shift_swap_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_swap_requests_id'), table_name='shift_swap_requests')
    op.drop_table('shift_swap_requests')
    op.drop_index(op.f('ix_staff_schedules_id'), table_name='staff_schedules')
    op.drop_table('staff_schedules')
    op.drop_index(op.f('ix_staff_performance_id'), table_name='staff_performance')
    op.drop_table('staff_performance')
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    # ### end Alembic commands ###
