"""Add kitchen display system models

Revision ID: 41fb0c013a86
Revises: 0f31aecb9b1c
Create Date: 2026-03-07 05:18:00.499266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41fb0c013a86'
down_revision: Union[str, Sequence[str], None] = '0f31aecb9b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kitchen_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('printer_ip', sa.String(length=45), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_kitchen_stations_id'), 'kitchen_stations', ['id'], unique=False)
    op.create_table('kds_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['kitchen_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kds_messages_id'), 'kds_messages', ['id'], unique=False)
    op.create_table('item_preparation_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=False),
    sa.Column('prep_count', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_preparation_times_id'), 'item_preparation_times', ['id'], unique=False)
    op.add_column('menu_items', sa.Column('kitchen_station_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'menu_items', 'kitchen_stations', ['kitchen_station_id'], ['id'])
    op.add_column('orders', sa.Column('priority', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('preparation_started_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('ready_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('estimated_completion', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'estimated_completion')
    op.drop_column('orders', 'ready_at')
    op.drop_column('orders', 'preparation_started_at')
    op.drop_column('orders', 'priority')
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.drop_column('menu_items', 'kitchen_station_id')
    op.drop_index(op.f('ix_item_preparation_times_id'), table_name='item_preparation_times')
    op.drop_table('item_preparation_times')
    op.drop_index(op.f('ix_kds_messages_id'), table_name='kds_messages')
    op.drop_table('kds_messages')
    op.drop_index(op.f('ix_kitchen_stations_id'), table_name='kitchen_stations')
    op.drop_table('kitchen_stations')
    # ### end Alembic commands ###
