"""Add customer analytics and RFM segmentation models

Revision ID: f48514f3d0fb
Revises: 362f3ed8cd56
Create Date: 2026-03-07 05:25:01.765220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f48514f3d0fb'
down_revision: Union[str, Sequence[str], None] = '362f3ed8cd56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('segment_type', sa.String(length=20), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_count', sa.Integer(), nullable=True),
    sa.Column('avg_order_value', sa.Float(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_customer_segments_id'), 'customer_segments', ['id'], unique=False)
    op.create_table('customer_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('min_spent', sa.Float(), nullable=False),
    sa.Column('max_spent', sa.Float(), nullable=True),
    sa.Column('points_multiplier', sa.Float(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_customer_tiers_id'), 'customer_tiers', ['id'], unique=False)
    op.create_table('customer_behaviors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('behavior_type', sa.String(length=50), nullable=False),
    sa.Column('behavior_data', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_behaviors_id'), 'customer_behaviors', ['id'], unique=False)
    op.create_table('customer_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('interaction_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_interactions_id'), 'customer_interactions', ['id'], unique=False)
    op.create_table('customer_lifetime_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('current_clv', sa.Float(), nullable=True),
    sa.Column('predicted_clv', sa.Float(), nullable=True),
    sa.Column('avg_monthly_value', sa.Float(), nullable=True),
    sa.Column('churn_probability', sa.Float(), nullable=True),
    sa.Column('loyalty_score', sa.Float(), nullable=True),
    sa.Column('next_visit_probability', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_lifetime_values_id'), 'customer_lifetime_values', ['id'], unique=False)
    op.create_table('customer_segment_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['customer_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_segment_members_id'), 'customer_segment_members', ['id'], unique=False)
    op.add_column('customers', sa.Column('tier_id', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('last_visit_date', sa.DateTime(), nullable=True))
    op.add_column('customers', sa.Column('visit_count', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('avg_order_value', sa.Float(), nullable=True))
    op.add_column('customers', sa.Column('preferred_items', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('loyalty_score', sa.Float(), nullable=True))
    op.add_column('customers', sa.Column('churn_risk', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'customers', 'customer_tiers', ['tier_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'churn_risk')
    op.drop_column('customers', 'loyalty_score')
    op.drop_column('customers', 'preferred_items')
    op.drop_column('customers', 'avg_order_value')
    op.drop_column('customers', 'visit_count')
    op.drop_column('customers', 'last_visit_date')
    op.drop_column('customers', 'tier_id')
    op.drop_index(op.f('ix_customer_segment_members_id'), table_name='customer_segment_members')
    op.drop_table('customer_segment_members')
    op.drop_index(op.f('ix_customer_lifetime_values_id'), table_name='customer_lifetime_values')
    op.drop_table('customer_lifetime_values')
    op.drop_index(op.f('ix_customer_interactions_id'), table_name='customer_interactions')
    op.drop_table('customer_interactions')
    op.drop_index(op.f('ix_customer_behaviors_id'), table_name='customer_behaviors')
    op.drop_table('customer_behaviors')
    op.drop_index(op.f('ix_customer_tiers_id'), table_name='customer_tiers')
    op.drop_table('customer_tiers')
    op.drop_index(op.f('ix_customer_segments_id'), table_name='customer_segments')
    op.drop_table('customer_segments')
    # ### end Alembic commands ###
